### ISSUE TITLE
Error message when running sorcery.py

### ISSUE THREAD

**Issue by philtech-oh** [mgupton/sorcery#1]
When running the latest installed sorcery package, I get this response:

root@inf-web00:[sorcery-master]# python sorcery.py host name-me \
> --api_key=################################### --dc=ashburn \
> --cid=####################################### --name=inf-web00
  File "sorcery.py", line 438
    print(err_msg, file=sys.stderr)
                       ^
SyntaxError: invalid syntax

**Comment by mgupton** [comment]
Please let me know what version of Python you are using. Python 3.x is required.

**Comment by philtech-oh** [comment]
We are running the default CentOS Python distribution, which is Python 2.7.5.  Unfortunately, upgrading to Python 3 is probably hot feasible for us.  Still, apologies for not noting the version requirement.
